### ISSUE TITLE
doesn't work - class name is wrong

### ISSUE THREAD

**Issue by aspiers** [steinwurf/slack-also-send-to-channel-default-on-chrome-extension#1]
Thanks for the great idea but it doesn't work any more.  Looks like Slack must have changed their CSS to [BEM](http://getbem.com/) or something because the class name is no longer reply_broadcast_toggle:

```html
<input id="p-thread_footer__broadcast_checkbox--CG4PM1PEK-1551446455.002100--threads-flexpane" type="checkbox" tabindex="0" class="c-input_checkbox p-threads_footer__broadcast_checkbox">
```

**Comment by jpihl** [comment]
Oh, I hadn't noticed.
Thanks for letting me know.
I have no experience with these special "naming schemes". Would you be able to provide a fix for this?

**Comment by aspiers** [comment]
Just change it to `p-threads_footer__broadcast_checkbox` I guess?

**Comment by aspiers** [comment]
I would submit a PR but I don't know how to test - not done extension development before.

**Comment by jpihl** [comment]
Ah obviously :man_facepalming: I'll look into it :) Thanks again.

**Comment by aspiers** [comment]
Awesome thanks!  How long before the extension gets updated in the store?

**Comment by jpihl** [comment]
It says "about 60 minutes" so it should be available now. :) The newest version is currently 1.0.3 .

**Comment by aspiers** [comment]
Yup - got it! It's checking the box correctly although I don't think it's having the desired effect.  I wonder if a different event handler needs to be triggered maybe ...

**Comment by jpihl** [comment]
Hmm, it's not working for me either. that's too bad. This will probably require more work to figure out (if at all possible).
If you want to look into this, I added some info about how to install the extension locally in the README.
