### ISSUE TITLE
doesn't work - button checked but ineffective

### ISSUE THREAD

**Issue by aspiers** [steinwurf/slack-also-send-to-channel-default-on-chrome-extension#2]
After #1, the button is now automatically checked but has no effect, therefore the extension is still effectively non-functional.

**Comment by jpihl** [comment]
Yes, it's very annoying. I'm not sure how to fix it though. I'll put a note about the issue in the README. 

Hopefully someone who has the time and know-how will come along and fix it :) Or even better Slack will implement this feature themselves :crossed_fingers:

**Comment by aspiers** [comment]
I suspect it doesn't work due to

    element.checked = true;

Maybe it's necessary to change this to

    element.click();

?

**Comment by jpihl** [comment]
You were right! But there were some other issues as well. As far as I can tell the extension is finally working.

I'll update the extension on the store ASAP.

**Comment by jpihl** [comment]
The update is live :+1:

**Comment by aspiers** [comment]
Woohoo, works great!!! Thanks so much :-)

**Comment by jpihl** [comment]
Fantastic! Glad to finally be of help ;) Hopefully Slack won't change the way they do things for some time now :crossed_fingers:
