### ISSUE TITLE
stopped working for first message

### ISSUE THREAD

**Issue by aspiers** [steinwurf/slack-also-send-to-channel-default-on-chrome-extension#3]
Something seems to have changed because it was working perfectly recently, but now the checkbox does not get ticked the first time I start writing a message into an open thread.  However after sending that message, it gets enabled in time for future messages.

**Comment by jpihl** [comment]
Hi @aspiers, thanks for reporting the issue - a fix should have been published.

**Comment by aspiers** [comment]
Brilliant thanks!
